name: Verify Pull Request

on:
  pull_request: { }
  workflow_dispatch: { }

jobs:
  fmod:
    name: Build FMOD
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: ./.github/actions/fmod
      - uses: actions/upload-artifact@v3
        with:
          name: FMOD Build
          path: .fmod/Build
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    needs: fmod
    timeout-minutes: 15
    strategy:
      matrix:
        targetPlatform:
          - StandaloneWindows64
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: actions/download-artifact@v3
        with:
          name: FMOD Build
          path: .fmod/Build
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          gitPrivateToken: ${{ secrets.PACKAGES_TOKEN }}
          unityVersion: 2022.3.6f1
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Tag
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build/${{ matrix.targetPlatform }}
